### ISSUE TITLE
coverage report is crashing when running with several connections

### ISSUE THREAD

**Issue by jgebal** [rsim/ruby-plsql-spec#20]
To reproduce:
place 2 connection definitions in database.yml
have a test (that utilizes one of the connections)
execute
plsql-spec --coverage

And you get:
```
Running all specs from spec/
stmt.c:250:in oci8lib_191.so: ORA-00942: table or view does not exist (OCIError)
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-oci8-2.1.8-x86-mingw32/lib/oci8/cursor.rb:126:in `exec'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-0.5.3/lib/plsql/oci_connection.rb:109:in `exec'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-0.5.3/lib/plsql/oci_connection.rb:94:in `new_from_query'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-0.5.3/lib/plsql/oci_connection.rb:144:in `cursor_from_query'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-0.5.3/lib/plsql/connection.rb:116:in `select_all'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-0.5.3/lib/plsql/sql_statements.rb:10:in `select_all'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-spec-0.4.0/lib/plsql/coverage.rb:106:in `coverage_data'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-spec-0.4.0/lib/plsql/coverage.rb:74:in `report'
        from c:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-plsql-spec-0.4.0/lib/plsql/coverage.rb:66:in `report'
        from C:/Users/Jacek/RubymineProjects/utplsql_vs_plsql_spec/spec/spec_helper.rb:43:in `block (2 levels) in <top (required)>'
        from C:/Users/Jacek/RubymineProjects/utplsql_vs_plsql_spec/spec/spec_helper.rb:36:in `each'
        from C:/Users/Jacek/RubymineProjects/utplsql_vs_plsql_spec/spec/spec_helper.rb:36:in `block in <top (required)>'
```

**Comment by javornikolov** [comment]
Are the two connections to the same database schema?

**Comment by jgebal** [comment]
Yes

*sent from mobile
24 cze 2015 08:09 "Yavor Nikolov" <notifications@github.com> napisał(a):

**Comment by jgebal** [comment]
The workaround for this issue is to have the plsql profiler tables created and accessible on the database prior to running the tests.
This way ruby-plsql-spec is not dropping the tables but is simply removing the data from it.

**Comment by javornikolov** [comment]
@jgebal could you check if  #22 helps?
