### ISSUE TITLE
Nokogiri too old

### ISSUE THREAD

**Issue by LeandroPT** [rsim/ruby-plsql-spec#46]
Hello,

Nokogiri gem dependency too old.

When trying to integrate with other tools, i get a dependency problem.

s.add_dependency(%q<nokogiri>.freeze, ["~> 1.6.0"]) ==> latest 1.8.2

is it possible to bump to latest and rebuild the gem?

**Comment by heidar** [comment]
There's a PR to fix this but I think it might need some discussion/pushing along, see #47

**Comment by javs1979** [comment]
> There's a PR to fix this but I think it might need some discussion/pushing along, see #47

The PR itself seems to fix the Nokogiri dependency problem. I am now able to run PL/SQL tests with ruby-plsql-spec in a standard manner. However, for some unknown reason, code coverage calculation with...

`plsql-spec run --coverage`

...stopped working. Here's the error...

```
❯ plsql-spec run --coverage

[...]

An error occurred while loading spec_helper.
Failure/Error: PLSQL::Coverage.start name

NoMethodError:
  undefined method `[]' for nil:NilClass
# ./spec/spec_helper.rb:35:in `block in <top (required)>'
# ./spec/spec_helper.rb:15:in `each'
# ./spec/spec_helper.rb:15:in `<top (required)>'
No examples found.

[...]
```
Any idea what might causing this ? I've rebuilt `ruby-plsql-spec` in version `0.5.1` (with the exact same changes as #47), then reinstalled, to no avail.

What do you think, @heidar ?
